# permissions for end users to edit controlplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: controlplane-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: control-plane-operator
    app.kubernetes.io/part-of: control-plane-operator
    app.kubernetes.io/managed-by: kustomize
  name: controlplane-editor-role
rules:
- apiGroups:
  - core.orchestrate.cloud.sap
  resources:
  - controlplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.orchestrate.cloud.sap
  resources:
  - controlplanes/status
  verbs:
  - get
