# permissions for end users to edit crossplanepackagerestrictions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: control-plane-operator
    app.kubernetes.io/managed-by: kustomize
  name: crossplanepackagerestriction-editor-role
rules:
- apiGroups:
  - core.orchestrate.cloud.sap
  resources:
  - crossplanepackagerestrictions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.orchestrate.cloud.sap
  resources:
  - crossplanepackagerestrictions/status
  verbs:
  - get
