# permissions for end users to view releasechannels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: releasechannel-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: control-plane-operator
    app.kubernetes.io/part-of: control-plane-operator
    app.kubernetes.io/managed-by: kustomize
  name: releasechannel-viewer-role
rules:
- apiGroups:
  - core.orchestrate.cloud.sap
  resources:
  - releasechannels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.orchestrate.cloud.sap
  resources:
  - releasechannels/status
  verbs:
  - get
