---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.orchestrate.cloud.sap
  resources:
  - releasechannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.orchestrate.cloud.sap
  resources:
  - releasechannels/finalizers
  verbs:
  - update
- apiGroups:
  - core.orchestrate.cloud.sap
  resources:
  - releasechannels/status
  verbs:
  - get
  - patch
  - update
