apiVersion: core.orchestrate.cloud.sap/v1beta1
kind: ControlPlane
metadata:
  name: controlplane-sample
spec:
  target:
    # read kubeconfig from secret
    kubeconfigRef:
      name: mykubeconfig
      namespace: default
      key: customMapKey
    fluxServiceAccount:
      name: flux-deployer
      namespace: default
  crossplane:
    version: 1.17.0
    providers:
      - name: kubernetes
        version: 0.14.1
  btpServiceOperator:
    version: 0.6.0
  certManager:
    version: 1.16.1
  externalSecretsOperator:
    version: 0.10.0
---
apiVersion: v1
kind: Secret
metadata:
  name: mykubeconfig
  namespace: default
type: Opaque
stringData:
  customMapKey: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: development
        cluster:
          certificate-authority: fake-ca-file
          server: https://1.2.3.4
    contexts:
      - name: development
        context:
          cluster: development
          user: development
    current-context: development
    preferences: {}
    users:
      - name: development
        user:
          client-certificate: fake-cert-file
          client-key: fake-key-file
---
apiVersion: core.orchestrate.cloud.sap/v1beta1
kind: CrossplanePackageRestriction
metadata:
  name: default
spec:
  providers:
    registries:
      - xpkg.upbound.io
    packages: []
  configurations:
    registries: []
    packages: []
  functions:
    registries: []
    packages: []